# Generated by Django 4.2.5 on 2023-09-17 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_chapter_id_alter_course_id_alter_section_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='number',
            field=models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
